version: '3'

services:
  nginx:
      build: ./nginx
      links:
        - nodejs:nodejs
      ports:
          - "8080:80"
          - "8443:443"
  nodejs:
      build: ./nodejs
      ports:
          - "3000:3000"